---
- name: Clone salting macOS repo
  hosts: all
  become: true
  gather_facts: false

  vars:
    repo_url: "https://github.com/mrbrown89/saltyMac.git"
    repo_branch: "main"
    repo_dest: "/opt/saltyMac"

  tasks:
    - name: Clone salting macOS repo
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        version: "{{ repo_branch }}"
        update: yes
