---
- name: Disable system sleep
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Turn system sleep off
      command: /usr/sbin/systemsetup -setsleep Off
      ignore_errors: true
