include:
  - security.fireWall
  - security.terminalKeyboard
  - security.auditControl
  - security.disableRemoteAppleEvents
  - security.disableRootShell
  - security.sudoTimeout
  - security.nfsServer
  - security.disableAutoLogin
  - security.disableGuest
  - security.networkTime
